jat_extranet:
    resource: "@JatExtranetBundle/Controller/"
    type:     annotation
    prefix:   /

jat_backend:
    resource: "@JatBackendBundle/Controller/"
    type:     annotation
    prefix:   /

jat_frontend:
    resource: "@JatFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

