acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
acme_hello_homepage:
  pattern:  /test/{name}
  defaults: { _controller: AcmeHelloBundle:Default:test }
